### ISSUE TITLE
Several memory management issues

### ISSUE THREAD

**Issue by rmaddy** [liveservices/LiveSDK-for-iOS#61]
I'm using the latest version (5.6.1) and I have found a few memory management issues.

1. LiveConnectClientCore.m. In the `refreshSessionWithDelegate:userState:` method, the assignment to the `authRefreshRequest` ivar needs to be changed to `self.authRefreshRequest` or the `autorelease` needs to be removed.

2. LiveAuthStorage.m. In the `initWithClientId:` method, the assignment to `_clientId` needs a `copy` (or `retain`). This problem doesn't appear when passing in a string literal but it causes a crash otherwise.

**Comment by aclev** [comment]
Hi @rmaddy Thanks for the input! Can you submit a pull request with the changes listed?

**Comment by rmaddy** [comment]
Sorry but I don’t know git well enough to know how to create a pull request.

Rick

**Comment by aclev** [comment]
Hi @rmaddy  Does the branch here solve your issues https://github.com/aclev/LiveSDK-for-iOS/tree/fixMemoryIssues ?

**Comment by rmaddy** [comment]
That seems OK though the dealloc method should access the ivar directly, not go through the property.

**Comment by aclev** [comment]
Agreed.  In this case however we need to call the cancel method on the LiveAuthRefreshRequest before we dealloc, just incase the request is still running.  if this is the case it could call its delegate methods on a dealloc delegate.  If autolease is removed we will have a memory leak because of the double retain on the property.  It is safe to call self at the beginning of dealloc as we have not yet dealloc any of the other properties.

**Comment by rmaddy** [comment]
You can still call the cancel method and set it to nil. Just call them directly on the ivar instead of the property.

Rick

**Comment by aclev** [comment]
You must call release on the ivar directly, otherwise it will result in memory leak.  Setting the property to nil will drop the retain count and dealloc the request properly.
